import '../../../globals.css';

import localFont from 'next/font/local';
import CampaignTabWrapper from '@/components/campagin/CampaignTabWrapper';

export const metadata = {
  title: 'Instantly.ai',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div className='flex flex-1 mx-8 my-3'>
      <CampaignTabWrapper>{children}</CampaignTabWrapper>
    </div>
  );
}
